object Versions {
    const val gradle = "4.0.1"
    const val kotlin = "1.4.10"
    const val KtxCore = "1.3.0"
    const val appCompact = "1.1.0"
    const val fragment = "1.2.5"
    const val cardView = "1.0.0"
    const val recyclerView = "1.1.0"
    const val constraintLayout = "1.1.3"
    const val lifecycle = "2.2.0"
    const val gson = "2.8.6"
    const val coroutine = "1.3.9"
    const val timber = "4.7.1"
    const val dagger = "2.27"
    const val googleMaterial = "1.2.0"
    const val coil = "0.11.0"
    const val securityCrypto = "1.0.0-rc02"
    const val retrofit = "2.9.0"
    const val okhttp = "4.7.2"
    const val stetho = "1.5.1"

    const val junit = "4.13"
    const val testCoreRunner = "1.2.0"
    const val espresso = "3.2.0"
    const val googleTruth = "1.0"
    const val coreTesting = "1.1.1"
    const val barista = "3.5.0"
    const val androidxJunit = "1.1.1"
    const val fragmentTesting = "1.2.5"
    const val robolectric = "4.3.1"
    const val navVersion = "2.3.5"

}